apiVersion: v1
kind: Service
metadata:
  name: {{ include "pritunl.fullname" . }}
  labels:
    {{- include "pritunl.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
    - name: vpn
      port: 1194
      targetPort: vpn
      protocol: UDP
  selector:
    {{- include "pritunl.selectorLabels" . | nindent 4 }}
