apiVersion: v1
kind: Service
metadata:
  name: {{ include "pritunl.fullname" . }}
  labels:
    {{- include "pritunl.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: vpn
      protocol: UDP
      name: vpn
  selector:
    {{- include "pritunl.selectorLabels" . | nindent 4 }}
